### ISSUE TITLE
Multiple Instances of a PLC Variable

### ISSUE THREAD

**Issue by muraliq24** [fbarresi/twincat-wpf-boilerplate#3]
If we have display same value twice in a view usins basics: PlcVariable(like in the image). Only one instance will show the value
![image](https://user-images.githubusercontent.com/57400173/108465312-c4b17080-72a7-11eb-8b92-7a4e4b55e68e.png)

**Comment by fbarresi** [comment]
Hi Murali!
Thank you for reporting this issue. 
I think the solution will not be hard to implement: variables should be internally cached for multiple usages.

**Comment by fbarresi** [comment]
Hi Murali!

I pushed 2 new commits. Can you please check in your application as well if this cache fix the problem?

An easy way to include my changes in your code is to fully copy this two files:

[DatabaseSevice.cs](https://github.com/fbarresi/twincat-wpf-boilerplate/blob/main/WpfApp.Logic/Services/DatabaseService.cs)
[BeckhoffPlc](https://github.com/fbarresi/twincat-wpf-boilerplate/blob/main/WpfApp.Logic/Hardware/BeckhoffPlc.cs)
