### ISSUE TITLE
App Freezing

### ISSUE THREAD

**Issue by muraliq24** [fbarresi/twincat-wpf-boilerplate#4]
Hi Fede,

When I tried to access a variable which is not in TC, the whole app freezes. I know there is a code to ignore the variables that couldn't be found in PLC. But it doesn't seem to work. Can you please check?

Thanks,
Murali

**Comment by fbarresi** [comment]
Hi!

I think I fixed it.

Pleas try out the new code in the same way described in #3 .

**Comment by muraliq24** [comment]
Thanks Fede, Its working now
